---

- name: create user accounts and add users to groups
  user:
    name: "{{ item }}"
    groups: "sudo"
    shell: "/bin/bash"
  with_items: "{{ users }}"
  
- name: add ssh-keys to users
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
  with_items: "{{ users }}"

