version: "3.3"

services:
  traefik:
    image: "traefik:latest"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - /opt/docker/config/traefik/acme.json:/acme.json
      - /opt/docker/config/traefik/traefik.toml:/traefik.toml
    networks:
      - traefik

networks:
  traefik:
    external: true
